Create Database IoT;
USE IoT;
Create TABLE Users
(
Email VARCHAR(50) NOT NULL,
FName VARCHAR(100) NOT NULL,
SName VARCHAR(100) NOT NULL,
CONSTRAINT PK_Email PRIMARY KEY (Email)
);

Create TABLE Locations
(
ID INT NOT NULL AUTO_INCREMENT,
Latitude DECIMAL(10,8) NOT NULL,
Longitude DECIMAL(11,8) NOT NULL,
TimeStamp TIMESTAMP NOT NULL,
Email VARCHAR(50) NOT NULL,
CONSTRAINT PK_ID PRIMARY KEY (id),
CONSTRAINT FK_Email FOREIGN KEY (Email)
REFERENCES Users(Email)
);

Create TABLE Sensers
(
ID INT NOT NULL AUTO_INCREMENT,
SensorName VARCHAR(15) NOT NULL,
SensorValue BOOLEAN NOT NULL,
TimeStamp TIMESTAMP NOT NULL,
Email VARCHAR(50) NOT NULL,
CONSTRAINT PK_ID_1 PRIMARY KEY (ID),
CONSTRAINT FK_Email_1 FOREIGN KEY (Email)
REFERENCES Users(Email)
);

INSERT INTO Users VALUES ("hamza_05@hotmail.co.uk","Hamza","Ghani");
